# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'FOSA' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!
  pod 'AvoidCrash', '~> 2.5.2'
  
  pod 'FMDB'
  
  pod 'AFNetworking', '~> 3.0'
  
  # Pods for FOSA

  target 'FOSATests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FOSAUITests' do
    # Pods for testing
  end

end
